import "dart:io";

import "package:dam/data.dart";
import "package:dam/utils.dart";

import "service.dart";

String _header = "# This Caddyfile was auto-generated by the DAM tool";

String _caddyfilePrefix = """
{
  log {
    output file /var/log/caddy/caddy.log
    format json
  }
}

(logging) {
  log {
    output file /var/log/caddy/{args[0]}.access.log {
      roll_size 10kb
      roll_keep 5
      roll_uncompressed
      roll_local_time
    }
  }
}

(block_robots) {
  respond /robots.txt 200 {
    body "User-agent: *
    Disallow: /"
    close
  }
}
""";

String _caddyfileSuffix = """
:80, :443 {
  import logging misc
  respond "Access denied" 403 {
    close
  }
}
""";

class CaddyService extends AppService<WebServerConfig> {
  final Directory dir = Directory(AppService.root / "caddy");

  @override
  String generate(App app, WebServerConfig config) {
    final buffer = StringBuffer();
    buffer.writeln(_header);
    buffer.writeln("# For more details, see: ${app.configFile.absolutePath}");
    buffer.writeln("${config.domain} {");
    buffer.writeln("  import logging ${app.name}");
    buffer.writeln("  root * /srv/${app.name}");
    if (config.blockCrawlers) {
      buffer.writeln("  handle /robots.txt {");
      buffer.writeln("    import block_robots");
      buffer.writeln("  }");
    }
    buffer.writeln("  handle {");
    if (config.reverseProxy case final ReverseProxyConfig proxy) {
      if (proxy.urlPrefix case final String prefix) {
        buffer.writeln("    reverse_proxy $prefix localhost:${proxy.port}");
      } else {
        buffer.writeln("    reverse_proxy localhost:${proxy.port}");
      }
    }
    if (config.fileServer != null) buffer.writeln("    file_server");
    buffer.writeln("  }");
    buffer.writeln("}");
    return buffer.toString();
  }

  File _getCaddyfile(App app) => File(dir / "${app.name}.caddy");
  List<File> _getAllCaddyfiles() {
    if (!dir.existsSync()) return [];
    return dir.listSync()
      .whereType<File>()
      .where((file) => file.path.endsWith(".caddy"))
      .toList();
  }

  @override
  Future<bool> isInstalled(App app) => _getCaddyfile(app).exists();

  @override
  Future<void> install(App app, WebServerConfig config) async {
    final contents = generate(app, config);
    final file = _getCaddyfile(app);
    await file.create(recursive: true);
    await file.writeAsString(contents);
    await generateMainCaddyfile();
  }

  @override
  Future<void> uninstall(App app) async {
    await _getCaddyfile(app).delete();
    await generateMainCaddyfile();
  }

  // TODO: Add other user-defined Caddyfile stuff here.
  Future<void> generateMainCaddyfile() async {
    final buffer = StringBuffer();
    buffer.writeln(_header);
    buffer.writeln(_caddyfilePrefix);
    for (final subfile in _getAllCaddyfiles()) {
      buffer.writeln("import ${subfile.absolutePath}");
    }
    buffer.writeln();
    buffer.write(_caddyfileSuffix);
    final file = File(dir / "Caddyfile");
    await file.create(recursive: true);
    await file.writeAsString(buffer.toString());
  }
}
