import "dart:io";

import "package:dam/data.dart";
import "package:dam/utils.dart";

import "service.dart";

String _header = "# This file was generated by DAM";

class CronService extends AppService<CronConfig> {
  Directory get dir => Directory("/etc/cron.d");

  File getFile(App app) => File(dir / app.name);

  @override
  String generate(App app, CronConfig config) {
    final buffer = StringBuffer();
    final user = LinuxUtils.user;
    buffer.writeln(_header);
    buffer.writeln("# For more information, see ${app.configFile.absolutePath}");
    buffer.writeln();
    buffer.writeln("${config.interval} $user ${config.executable}");
    return buffer.toString();
  }

  @override
  Future<bool> isInstalled(App app) async {
    return getFile(app).isInstalledByDam(_header);
  }

  Future<void> checkIfSafe(File file) async {
    if (!await file.isSafeToWrite(_header)) {
      throw DamError("The cron file ${file.absolutePath} was created by another service");
    }
  }

  @override
  Future<void> install(App app, CronConfig config) async {
    final contents = generate(app, config);
    final file = getFile(app);
    await checkIfSafe(file);
    await file.create(recursive: true);
    await file.writeAsString(contents);
  }

  @override
  Future<void> uninstall(App app) async {
    final file = getFile(app);
    await checkIfSafe(file);
    await file.delete();
  }
}
