import "dart:io";

import "package:dam/data.dart";
import "package:dam/utils.dart";

import "service.dart";

// NOTE: DO NOT CHANGE. This is used to identify DAM-written files.
String _header = "# This service was auto-generated by the DAM tool";

String _template({
  required File configFile,
  required String name,
  required Directory dir,
  required File executable,
}) => """
$_header
# See ${configFile.absolutePath} for more details.

[Unit]
Description="$name"
After=network-online.target

[Service]
WorkingDirectory=${dir.absolutePath}
ExecStart=${executable.absolutePath}
TimeoutStopSec=3

[Install]
WantedBy=multi-user.target
""";

class SystemdService extends AppService<SystemdConfig> {
  @override
  SystemdConfig? getConfig(AppConfig config) => config.systemd;

  @override
  String generate(App app, SystemdConfig config) =>
    _template(name: app.name, configFile: app.configFile, dir: app.dir, executable: File(app.dir / config.executableCommand));

  // TODO: Put the file somewhere else.
  // See: systemd-analyze --user unit-paths
  File getServiceFile(App app) => File("/etc/systemd/service/${app.name}.service");

  Future<void> checkIfSafe(File file) async {
    if (!await file.isSafeToWrite(_header)) {
      throw DamError("The service file ${file.path} is already registered to another service");
    }
  }

  @override
  Future<bool> isInstalled(App app) async {
    final file = getServiceFile(app);
    return file.isInstalledByDam(_header);
  }

  @override
  Future<void> install(App app, SystemdConfig config, {required bool dryRun}) async {
    logger.info("Installing systemd configuration");
    final contents = generate(app, config);
    final file = getServiceFile(app);
    logger.debug("Writing systemd unit file to ${file.absolutePath}");
    logger.logFileContent(contents);
    if (!dryRun) {
      await checkIfSafe(file);
      await file.writeAsString(contents);
    }
    logger.debug("Enabling the service");
    await logger.runProcess("sudo", ["systemctl", "enable", app.name], dryRun: dryRun);
    await logger.runProcess("sudo", ["systemctl", "start", "service"], dryRun: dryRun);
  }

  @override
  Future<void> uninstall(App app, {required bool dryRun}) async {
    logger.info("Uninstalling systemd configuration");
    logger.debug("Disabling the service");
    await logger.runProcess("sudo", ["systemctl", "stop", "service"], dryRun: dryRun);
    await logger.runProcess("sudo", ["systemctl", "disable", "service"], dryRun: dryRun);
    final file = getServiceFile(app);
    logger.debug("Deleting the systemd unit file at ${file.absolutePath}");
    if (!dryRun) {
      await checkIfSafe(file);
      await file.delete();
    }
  }
}
